### ISSUE TITLE
Incorrect JSON with floating point numbers

### ISSUE THREAD

**Issue by Zhigalin** [eteran/cpp-json#10]
Hello,
depending on the system locale (at least on linux) floating point numbers may be rendered with a comma instead of a dot, resulting in a malformed JSON.
This happen ad example with Italian, Russian, French or German locales.

**Comment by eteran** [comment]
Thanks for the report, I'll look into this and work on a patch ASAP!

**Comment by eteran** [comment]
Please let me know if this fixes the issue as expected.

**Comment by eteran** [comment]
Closing, feel free to re-open if the problem persists.

**Comment by Zhigalin** [comment]
It worked, thank you very much, sorry for the late reply
