### ISSUE TITLE
json::has_key throws an error: 'json::invalid_index'

### ISSUE THREAD

**Issue by mcordova1967** [eteran/cpp-json#14]
Hello, I am trying to use has_key to test if an attribute is present before reading it, but the exception mentioned in the tittle is being thrown.

The JSON:

```
[
	{
		"uri": "/ms/query/search",
		"sql": "execute sp_getSalesByCategory $date1, $date2",
		"function": "dbget",
		"fields": [
			{"name": "date1", "type": "date", "required": "true"},
			{"name": "date2", "type": "date", "required": "true"}
		]
	},
	{
		"uri": "/ms/status",
		"function": "getServerInfo"
	}
]

```

I am using an array and on each iteration I am testing the existence of certain attributes, like "sql" which may be optional.

```

		std::ifstream file("./service.json");
		if (file.is_open()) {

			json::value json = json::parse(file);
			const json::array &a = as_array(json);
			for(auto it = a.begin(); it != a.end(); ++it) {
				const json::value &v = *it;
				std::cout <<  json::stringify(v) << std::endl;
				std::string uri{  json::to_string(v["uri"]) };
				std::cout << " reading ... " << uri << std::endl;
				std::string func{  json::to_string(v["function"]) };
				std::string sql{ "" };
				if(json::has_key(v, "sql")) {
					std::cout << " reading sql..." << std::endl;
					sql = json::to_string(v["sql"]);
				}
//more code follow here....

```

As soon as this is executed `if(json::has_key(v, "sql")) {` the program terminates with this message:

terminate called after throwing an instance of `json::invalid_index`

What I am doing wrong?

Thank you,
Martín

**Comment by eteran** [comment]
Interesting, I'll double check and try to replicate the issue and see if there is a quick and easy fix.

**Comment by mcordova1967** [comment]
Thank you very much!

**Comment by eteran** [comment]
As a follow-up, Here are the functions which I think can throw `invalid_index`:

`array::at`
`array::operator[]`
`object::at`
`value::at`
`value::operator[]`
`value::create`

Possible I missed some due to call stacks, but those are the obvious ones.

**Comment by mcordova1967** [comment]
Thanks for the prompt reply, I will download latest master and test again and let you know the results ASAP.

**Comment by eteran** [comment]
Great. If if you are still running into the issue, please try my test case and see if that works for you. If it does, then I think we may be looking at the wrong line number, if it doesn't, well, there is something strange going on ;-)

**Comment by mcordova1967** [comment]
I downloaded the latest version and it worked! thanks a lot for the support, this is a very nice component.
I am sorry if my report was misleading.
