### ISSUE TITLE
Support all arithmetic types

### ISSUE THREAD

**Issue by trueqbit** [eteran/cpp-json#6]
I have noticed that `value` only accepts signed 32-bit integer numbers, no unsigned or 64-bit. Is there any reasoning behind?

The only reason I can think of is Javascript's limitation of integer numbers being confined in the range of `[Number.MIN_SAFE_INTEGER, Number.MAX_SAFE_INTEGER]`.

However, a JSON library shouldn't be limited by Javascript's limits, so I propose a template constructor accepting all arithmetic types. We could even choose to make 64-bit integer constructors explicit, as JSON is often used from Javascript.

**Comment by eteran** [comment]
Your patch resolves this right?

**Comment by trueqbit** [comment]
That's right, question is whether you agree with implicit conversions from all arithmetic types.

And I see now that I put the wrong issue number in the commit message... Let me reissue the pull request.

**Comment by eteran** [comment]
PR already accepted :-) was just wondering if I should consider this issue closed.
